name: "set up AWS infrastructure"

on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_access_secret:
        required: true

jobs:
  create-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2